// Code generated by internal/codegen from contract/contract.json (core 2cc44c16f516). DO NOT EDIT.

package oblodai

const (
	// ContractCoreCommit is the core revision the contract snapshot was exported from.
	ContractCoreCommit = "2cc44c16f516d6c26d6290dcada40b7ed814d6de"
	// ContractExportedAt is when that snapshot was taken.
	ContractExportedAt = "2026-08-26T15:26:29Z"
	// ContractHash is the SHA-256 of contract/contract.json; it identifies the wire contract.
	ContractHash = "de2c4a5d15d13036fc63d301c1b28209f47189e54692fcb9523bb30e5fa39652"
)
