// Code generated by internal/codegen from contract/contract.json (core bfca971cce71). DO NOT EDIT.

package oblodai

// Request bodies, one struct per route the core documents a DTO for. Field names, required
// flags, examples and documentation all come from the contract snapshot: an optional field is
// omitted from the JSON when empty, a required one is always sent.

// APIAllowlistAddParams is the request body of POST /v1/api-allowlist/add.
type APIAllowlistAddParams struct {
	// IP or subnet in CIDR notation (203.0.113.7 or 203.0.113.0/24). Required. Example:
	// "203.0.113.0/24".
	CIDR string `json:"cidr"`
}

// APIAllowlistEnableParams is the request body of POST /v1/api-allowlist/enable.
type APIAllowlistEnableParams struct {
	// true — accept API calls only from listed addresses; false — the list is kept but not
	// enforced. Required. Example: true.
	Enabled bool `json:"enabled"`
}

// APIAllowlistRemoveParams is the request body of POST /v1/api-allowlist/remove.
type APIAllowlistRemoveParams struct {
	// IP or subnet in CIDR notation (203.0.113.7 or 203.0.113.0/24). Required. Example:
	// "203.0.113.0/24".
	CIDR string `json:"cidr"`
}

// AutoWithdrawDeleteParams is the request body of POST /v1/auto-withdraw/delete.
type AutoWithdrawDeleteParams struct {
	// Asset whose auto-withdrawal to switch off. Required. Example: "USDT".
	Currency string `json:"currency"`
}

// AutoWithdrawSetParams is the request body of POST /v1/auto-withdraw/set.
type AutoWithdrawSetParams struct {
	// Destination address (the merchant's external wallet). Required. Example:
	// "TQrY8bkbpXKPt2LZbU8jqfnpFbUSF15sbx".
	Address string `json:"address"`

	// Asset to withdraw automatically. Required. Example: "USDT".
	Currency string `json:"currency"`

	// Threshold: the sweep runs once the available balance of the asset reaches this amount; empty
	// uses the network minimum. Example: "100".
	MinAmount Money `json:"min_amount,omitempty"`

	// Network of the destination address. Required. Example: "tron".
	Network Network `json:"network"`
}

// BatchInfoParams is the request body of POST /v1/batch/info.
type BatchInfoParams struct {
	// Batch id from the submit response. Required. Example: "9f4c1a2b-77de-4a55-9c1f-0e2b3d4a5f60".
	BatchID string `json:"batch_id"`

	// How many items to return in items (pagination). Example: 100.
	Limit *int `json:"limit,omitempty"`

	// Offset over items. Example: 0.
	Offset *int `json:"offset,omitempty"`
}

// PostClaimParams is the request body of POST /v1/claim/{token}.
type PostClaimParams struct {
	// Recipient address in the payout network. Required.
	Address string `json:"address"`

	// Memo/tag — only for networks where it is required.
	Memo string `json:"memo,omitempty"`

	// Claim code — if the sender set one on the link. After 10 incorrect attempts the link is
	// locked.
	Passcode string `json:"passcode,omitempty"`
}

// DocumentsJobsParams is the request body of POST /v1/documents/jobs.
type DocumentsJobsParams struct {
	// File format: pdf (default) or csv. CSV is generated without layout — cheaper for large
	// statements and loads into Excel/1C. Example: "csv".
	Format string `json:"format,omitempty"`

	// Start of the period, YYYY-MM-DD (defaults to the first day of the current month). Example:
	// "2025-01-01".
	From string `json:"from,omitempty"`

	// Report type: statement (operations), fees (commissions) or ledger (balance movements). Required.
	// Example: "statement".
	Kind string `json:"kind"`

	// Document language (default en). Example: "ru".
	Lang string `json:"lang,omitempty"`

	// End of the period, inclusive, YYYY-MM-DD (defaults to today). The period may span up to two
	// years. Example: "2026-08-19".
	To string `json:"to,omitempty"`
}

// DocumentsJobsInfoParams is the request body of POST /v1/documents/jobs/info.
type DocumentsJobsInfoParams struct {
	// Job id from the creation response. Required. Example: "6f1c…".
	JobID string `json:"job_id"`
}

// ExchangeRateListParams is the request body of POST /v1/exchange-rate/list.
type ExchangeRateListParams struct {
	// Currency code. If set, only its rate is returned. If empty or the body is {}, rates for all
	// currencies are returned. Example: "ETH".
	CurrencyFrom string `json:"currency_from,omitempty"`

	// Quote currency: USDT by default; any pricing asset, including fiats with a direct feed (EUR,
	// RUB, …).
	CurrencyTo string `json:"currency_to,omitempty"`

	// Page size, 1–100; default 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list; default 0.
	Offset *int `json:"offset,omitempty"`
}

// LinkCheckoutParams is the request body of POST /v1/link/{id}/checkout.
type LinkCheckoutParams struct {
	// Amount entered by the buyer, in the link's price currency; required for open and range, ignored
	// for fixed. Example: "10.00".
	Amount Money `json:"amount,omitempty"`

	// Settlement currency — the coin the buyer pays with; needed only if the link did not pin
	// pinned_currency. Example: "USDT".
	Currency string `json:"currency,omitempty"`

	// Settlement network; needed only if the link did not pin pinned_network. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Shop order number from the embedded widget (data-oblodai-order-id); carried over to the invoice
	// and to the webhook for matching with the order; not an idempotency key.
	OrderID string `json:"order_id,omitempty"`

	// Buyer email — the cheque is sent there automatically after payment. Example:
	// "buyer@example.com".
	PayerEmail string `json:"payer_email,omitempty"`
}

// MerchantsParams is the request body of POST /v1/merchants.
type MerchantsParams struct {
	// Owner email; must be unique across merchants. Required. Example: "owner@shop.example".
	Email string `json:"email"`

	// Display name of the merchant. Example: "Acme".
	Name string `json:"name,omitempty"`
}

// PaySelectParams is the request body of POST /v1/pay/{id}/select.
type PaySelectParams struct {
	// Selected payment currency. Required. Example: "USDT".
	Currency string `json:"currency"`

	// Selected network. Required. Example: "tron".
	Network Network `json:"network"`
}

// PaymentParams is the request body of POST /v1/payment.
type PaymentParams struct {
	// Under/overpayment tolerance, 0–5 %. Overrides the merchant setting.
	AccuracyPaymentPercent *float64 `json:"accuracy_payment_percent,omitempty"`

	// Private merchant data, echoed back in webhooks (not visible to the buyer).
	AdditionalData string `json:"additional_data,omitempty"`

	// Amount to pay, in currency. Required. Example: "10".
	Amount Money `json:"amount"`

	// Price currency code: any of the 23 fiats (USD, EUR, RUB, …) or any coin (USDT, BTC, …). JPY
	// and KRW have zero decimal places. Required. Example: "USD".
	Currency string `json:"currency"`

	// Allow paying up the remaining amount.
	IsPaymentMultiple *bool `json:"is_payment_multiple,omitempty"`

	// Revive an expired invoice by order_id instead of creating a new one.
	IsRefresh *bool `json:"is_refresh,omitempty"`

	// Invoice lifetime in seconds, 300–43200; default 3600. Values outside the range are clamped to
	// the nearest bound. Example: 3600.
	LifetimeSeconds *int `json:"lifetime_seconds,omitempty"`

	// Settlement network (e.g. tron, ethereum). Optional — see the currency and network selection
	// modes. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Merchant reference; idempotency key. Strongly recommended. Example: "order-1".
	OrderID string `json:"order_id,omitempty"`

	// Payer email. If set, a cheque is sent there automatically after payment; it is also the default
	// recipient for POST /v1/payment/send-email.
	PayerEmail string `json:"payer_email,omitempty"`

	// Deprecated: % of the network markup charged to the payer (0–100); payer-facing markups are
	// configured via discount.
	Subtract *int `json:"subtract,omitempty"`

	// Payment page theme: dark | light. Example: "dark".
	Theme string `json:"theme,omitempty"`

	// Settlement currency — the crypto used for payment. Defaults to currency (only if currency is a
	// coin); with a fiat price set it explicitly or omit it together with network. Example: "USDT".
	ToCurrency string `json:"to_currency,omitempty"`

	// Per-invoice webhook. Requires a registered endpoint (POST /v1/webhooks): delivery is signed with
	// its secret.
	URLCallback string `json:"url_callback,omitempty"`

	// "Back to shop" link on the payment page.
	URLReturn string `json:"url_return,omitempty"`

	// Redirect after successful payment.
	URLSuccess string `json:"url_success,omitempty"`
}

// PaymentAcceptedListParams is the request body of POST /v1/payment/accepted/list.
type PaymentAcceptedListParams struct {
	// Page size, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (newest first). Example: 0.
	Offset *int `json:"offset,omitempty"`
}

// PaymentAcceptedSetParams is the request body of POST /v1/payment/accepted/set.
type PaymentAcceptedSetParams struct {
	// The full list of currency+network pairs payers may use; an empty list accepts everything in the
	// catalog. Required.
	Accepted []PaymentAcceptedSetParamsAcceptedItem `json:"accepted"`
}

// PaymentAcceptedSetParamsAcceptedItem is an element of accepted in POST /v1/payment/accepted/set.
type PaymentAcceptedSetParamsAcceptedItem struct {
	// Asset code. Required. Example: "USDT".
	Currency string `json:"currency"`

	// Asset network. Required. Example: "tron".
	Network Network `json:"network"`
}

// PaymentAccuracySetParams is the request body of POST /v1/payment/accuracy/set.
type PaymentAccuracySetParams struct {
	// Tolerance in percent, 1–5. Required when enabled: true; ignored when enabled: false (reset to
	// 0). Capped at 5 %. Example: 2.
	AccuracyPercent *int `json:"accuracy_percent,omitempty"`

	// Enable/disable the tolerance. Required. Example: true.
	Enabled bool `json:"enabled"`
}

// PaymentAutorefundSetParams is the request body of POST /v1/payment/autorefund/set.
type PaymentAutorefundSetParams struct {
	// Refund the excess on overpayment (paid_over). Required. Example: true.
	Overpay bool `json:"overpay"`

	// Refund the funds on an expired underpayment (wrong_amount). Required. Example: true.
	Underpay bool `json:"underpay"`
}

// PaymentBatchParams is the request body of POST /v1/payment/batch.
type PaymentBatchParams struct {
	// What to do when an item fails: continue (default) — process the rest; stop — halt processing
	// after the first error. Example: "continue".
	OnError BatchOnError `json:"on_error,omitempty"`

	// Array of 1 to 5000 items — the same fields as POST /v1/payment; set order_id on every item:
	// results are matched by it and it protects against duplicates. Required.
	Payments []PaymentBatchParamsPaymentItem `json:"payments"`
}

// PaymentBatchParamsPaymentItem is an element of payments in POST /v1/payment/batch.
type PaymentBatchParamsPaymentItem struct {
	// Under/overpayment tolerance, 0–5 %. Overrides the merchant setting.
	AccuracyPaymentPercent *float64 `json:"accuracy_payment_percent,omitempty"`

	// Private merchant data, echoed back in webhooks (not visible to the buyer).
	AdditionalData string `json:"additional_data,omitempty"`

	// Amount to pay, in currency. Required. Example: "10".
	Amount Money `json:"amount"`

	// Price currency code: any of the 23 fiats (USD, EUR, RUB, …) or any coin (USDT, BTC, …). JPY
	// and KRW have zero decimal places. Required. Example: "USD".
	Currency string `json:"currency"`

	// Allow paying up the remaining amount.
	IsPaymentMultiple *bool `json:"is_payment_multiple,omitempty"`

	// Revive an expired invoice by order_id instead of creating a new one.
	IsRefresh *bool `json:"is_refresh,omitempty"`

	// Invoice lifetime in seconds, 300–43200; default 3600. Values outside the range are clamped to
	// the nearest bound. Example: 3600.
	LifetimeSeconds *int `json:"lifetime_seconds,omitempty"`

	// Settlement network (e.g. tron, ethereum). Optional — see the currency and network selection
	// modes. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Merchant reference; idempotency key. Strongly recommended. Required. Example: "order-1".
	OrderID string `json:"order_id"`

	// Payer email. If set, a cheque is sent there automatically after payment; it is also the default
	// recipient for POST /v1/payment/send-email.
	PayerEmail string `json:"payer_email,omitempty"`

	// Deprecated: % of the network markup charged to the payer (0–100); payer-facing markups are
	// configured via discount.
	Subtract *int `json:"subtract,omitempty"`

	// Payment page theme: dark | light. Example: "dark".
	Theme string `json:"theme,omitempty"`

	// Settlement currency — the crypto used for payment. Defaults to currency (only if currency is a
	// coin); with a fiat price set it explicitly or omit it together with network. Example: "USDT".
	ToCurrency string `json:"to_currency,omitempty"`

	// Per-invoice webhook. Requires a registered endpoint (POST /v1/webhooks): delivery is signed with
	// its secret.
	URLCallback string `json:"url_callback,omitempty"`

	// "Back to shop" link on the payment page.
	URLReturn string `json:"url_return,omitempty"`

	// Redirect after successful payment.
	URLSuccess string `json:"url_success,omitempty"`
}

// PaymentCancelParams is the request body of POST /v1/payment/cancel.
type PaymentCancelParams struct {
	// Your order reference. Example: "order-1".
	OrderID string `json:"order_id,omitempty"`

	// Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.
	UUID string `json:"uuid,omitempty"`
}

// PaymentDiscountListParams is the request body of POST /v1/payment/discount/list.
type PaymentDiscountListParams struct {
	// Page size, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (newest first). Example: 0.
	Offset *int `json:"offset,omitempty"`
}

// PaymentDiscountSetParams is the request body of POST /v1/payment/discount/set.
type PaymentDiscountSetParams struct {
	// Currency. Empty = global default for all coins. Example: "USDT".
	Currency string `json:"currency,omitempty"`

	// Percentage, from -99 to 99. Positive is a discount, negative is a markup. Required. Example: 3.
	DiscountPercent int `json:"discount_percent"`

	// Network. Empty = any network of this currency. Example: "tron".
	Network Network `json:"network,omitempty"`
}

// PaymentFeeConfigSetParams is the request body of POST /v1/payment/fee-config/set.
type PaymentFeeConfigSetParams struct {
	// Share of OUR commission paid by the buyer: 0 — the merchant pays (current behaviour), 100 —
	// the buyer pays and the invoice is issued with a markup. Applies to invoices created AFTER the
	// change. Required. Example: 100.
	PayerPaysPercent int `json:"payer_pays_percent"`
}

// PaymentHistoryParams is the request body of POST /v1/payment/history.
type PaymentHistoryParams struct {
	// Ignored on this route (payout history only). Example: "payout".
	Kind string `json:"kind,omitempty"`

	// Page size, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (newest first). Example: 0.
	Offset *int `json:"offset,omitempty"`

	// Filter by status (an exact value from the status vocabulary); empty returns all. Example:
	// "paid".
	Status PaymentStatus `json:"status,omitempty"`
}

// PaymentInfoParams is the request body of POST /v1/payment/info.
type PaymentInfoParams struct {
	// Your order reference. Example: "order-1".
	OrderID string `json:"order_id,omitempty"`

	// Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.
	UUID string `json:"uuid,omitempty"`
}

// PaymentLinkParams is the request body of POST /v1/payment/link.
type PaymentLinkParams struct {
	// Amount — for fixed mode; required in this mode. Example: "25.00".
	AmountFixed Money `json:"amount_fixed,omitempty"`

	// Amount mode: fixed | open | range. Required. Example: "open".
	AmountMode AmountMode `json:"amount_mode"`

	// Price currency — fiat (USD, EUR, RUB, …) or a coin; see pricing_currencies from GET
	// /v1/currencies. Required. Example: "USD".
	Currency string `json:"currency"`

	// Description on the payment page.
	Description string `json:"description,omitempty"`

	// Link lifetime in seconds from creation; 0 (default) — the link never expires.
	ExpiresInSeconds *int `json:"expires_in_seconds,omitempty"`

	// Upper bound — for range; required in this mode. Example: "1000.00".
	MaxAmount Money `json:"max_amount,omitempty"`

	// Lower bound: an optional floor for open, a required minimum for range. Example: "1.00".
	MinAmount Money `json:"min_amount,omitempty"`

	// Settlement currency (coin) pinned to the link; empty — the buyer chooses the coin. Example:
	// "USDT".
	PinnedCurrency string `json:"pinned_currency,omitempty"`

	// Settlement network pinned to the link; empty — the buyer chooses the network. Example: "tron".
	PinnedNetwork Network `json:"pinned_network,omitempty"`

	// Title on the payment page. Example: "Поддержать проект".
	Title string `json:"title,omitempty"`
}

// PaymentLinkInfoParams is the request body of POST /v1/payment/link/info.
type PaymentLinkInfoParams struct {
	// Page size for the link's payments, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Payment link identifier. Required. Example: "5d3f2a71-9c84-4b0e-8d17-3e6a2c9f1b40".
	LinkID string `json:"link_id"`

	// Offset within the link's payments. Example: 0.
	Offset *int `json:"offset,omitempty"`
}

// PaymentLinkListParams is the request body of POST /v1/payment/link/list.
type PaymentLinkListParams struct {
	// Page size, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (newest first). Example: 0.
	Offset *int `json:"offset,omitempty"`
}

// PaymentLinkToggleParams is the request body of POST /v1/payment/link/toggle.
type PaymentLinkToggleParams struct {
	// true — the link accepts payments; false — disabled (the page shows the link as inactive).
	// Required. Example: false.
	Active bool `json:"active"`

	// Payment link identifier. Required. Example: "5d3f2a71-9c84-4b0e-8d17-3e6a2c9f1b40".
	LinkID string `json:"link_id"`
}

// PaymentQRParams is the request body of POST /v1/payment/qr.
type PaymentQRParams struct {
	// Your order reference. Example: "order-1".
	OrderID string `json:"order_id,omitempty"`

	// Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.
	UUID string `json:"uuid,omitempty"`
}

// PaymentRefundParams is the request body of POST /v1/payment/refund.
type PaymentRefundParams struct {
	// Refund destination address. Defaults to the payment's payer_address; required only for
	// Bitcoin/UTXO.
	Address string `json:"address,omitempty"`

	// Partial amount. Defaults to the full amount received. Example: "10".
	Amount Money `json:"amount,omitempty"`

	// Network. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Your order reference for the payment. Either uuid or order_id is required. Example: "order-1".
	OrderID string `json:"order_id,omitempty"`

	// Optional refund idempotency key: distinguishes two different refunds with the same (payment,
	// address, amount); a repeat with the same value is deduplicated. This is not order_id.
	Reference string `json:"reference,omitempty"`

	// Payment id. Either uuid or order_id is required.
	UUID string `json:"uuid,omitempty"`
}

// PaymentResendParams is the request body of POST /v1/payment/resend.
type PaymentResendParams struct {
	// Your order reference. Example: "order-1".
	OrderID string `json:"order_id,omitempty"`

	// Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.
	UUID string `json:"uuid,omitempty"`
}

// PaymentResolveParams is the request body of POST /v1/payment/resolve.
type PaymentResolveParams struct {
	// accept — accept the partial payment, refund — return it to the payer. Required. Example:
	// "accept".
	Action string `json:"action"`

	// refund only: refund address. Defaults to the payment's recorded payer_address; if it is empty
	// (Bitcoin/UTXO) the address is required, otherwise refund.no_address.
	Address string `json:"address,omitempty"`

	// refund only: refund network, defaults to the payment network.
	Network Network `json:"network,omitempty"`

	// Your payment identifier. Example: "ord-1001".
	OrderID string `json:"order_id,omitempty"`

	// refund only: your refund deduplication key.
	Reference string `json:"reference,omitempty"`

	// Payment UUID. Either uuid or order_id is required.
	UUID string `json:"uuid,omitempty"`
}

// PaymentSendEmailParams is the request body of POST /v1/payment/send-email.
type PaymentSendEmailParams struct {
	// Where to send it. Defaults to the payer_email set on the payment. Example: "buyer@example.com".
	Email string `json:"email,omitempty"`

	// Your order reference. Example: "order-1".
	OrderID string `json:"order_id,omitempty"`

	// Payment id in Oblodai. Either uuid or order_id is required.
	UUID string `json:"uuid,omitempty"`
}

// PaymentServicesParams is the request body of POST /v1/payment/services.
type PaymentServicesParams struct {
	// Page size, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (newest first). Example: 0.
	Offset *int `json:"offset,omitempty"`
}

// PaymentTestingWebhookParams is the request body of POST /v1/payment/testing-webhook.
type PaymentTestingWebhookParams struct {
	// Status in the body. Default paid. Example: "paid".
	Status PaymentStatus `json:"status,omitempty"`

	// Where to send the test body. If not provided, delivery goes to the project's registered
	// endpoint; without an endpoint it fails with webhook.no_endpoint. Signed with the project
	// endpoint's secret, including when url is passed explicitly. Example:
	// "https://shop.example/hook".
	URL string `json:"url,omitempty"`
}

// PayoutParams is the request body of POST /v1/payout.
type PayoutParams struct {
	// Recipient address. Required.
	Address string `json:"address"`

	// Payout amount, in currency. Required. Example: "25".
	Amount Money `json:"amount"`

	// Currency code (for example USDT). Required. Example: "USDT".
	Currency string `json:"currency"`

	// Fund the payout by converting the balance. USDT → currency only. Example: "USDT".
	FromCurrency string `json:"from_currency,omitempty"`

	// Who pays the network fee: true — amount+fee is debited from the balance and the recipient
	// receives amount; false — the recipient receives amount-fee; not provided — the project
	// fee-config.
	IsSubtract *bool `json:"is_subtract,omitempty"`

	// Destination tag/memo (TON Jetton). Maximum 120 characters.
	Memo string `json:"memo,omitempty"`

	// Network (tron, ethereum, …). Required for coins with several networks. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Your payout number; idempotency key. Required. Example: "payout-1".
	OrderID string `json:"order_id"`

	// Origin label: api (default) or manual.
	Source string `json:"source,omitempty"`

	// Custom webhook URL for this payout (passes the SSRF check). Requires a registered endpoint (POST
	// /v1/webhooks): delivery is signed with its secret.
	URLCallback string `json:"url_callback,omitempty"`
}

// PayoutApproveParams is the request body of POST /v1/payout/approve.
type PayoutApproveParams struct {
	// Payout id. Required.
	UUID string `json:"uuid"`
}

// PayoutBatchParams is the request body of POST /v1/payout/batch.
type PayoutBatchParams struct {
	// What to do when an item fails: continue (default) — process the rest; stop — halt processing
	// after the first error. Example: "continue".
	OnError BatchOnError `json:"on_error,omitempty"`

	// Array of 1 to 5000 items — the same fields as POST /v1/payout; order_id is required on every
	// item and serves as the idempotency key: a repeat returns the already created payout. Required.
	Payouts []PayoutBatchParamsPayoutItem `json:"payouts"`
}

// PayoutBatchParamsPayoutItem is an element of payouts in POST /v1/payout/batch.
type PayoutBatchParamsPayoutItem struct {
	// Recipient address. Required.
	Address string `json:"address"`

	// Payout amount, in currency. Required. Example: "25".
	Amount Money `json:"amount"`

	// Currency code (for example USDT). Required. Example: "USDT".
	Currency string `json:"currency"`

	// Fund the payout by converting the balance. USDT → currency only. Example: "USDT".
	FromCurrency string `json:"from_currency,omitempty"`

	// Who pays the network fee: true — amount+fee is debited from the balance and the recipient
	// receives amount; false — the recipient receives amount-fee; not provided — the project
	// fee-config.
	IsSubtract *bool `json:"is_subtract,omitempty"`

	// Destination tag/memo (TON Jetton). Maximum 120 characters.
	Memo string `json:"memo,omitempty"`

	// Network (tron, ethereum, …). Required for coins with several networks. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Your payout number; idempotency key. Required. Example: "payout-1".
	OrderID string `json:"order_id"`

	// Origin label: api (default) or manual.
	Source string `json:"source,omitempty"`

	// Custom webhook URL for this payout (passes the SSRF check). Requires a registered endpoint (POST
	// /v1/webhooks): delivery is signed with its secret.
	URLCallback string `json:"url_callback,omitempty"`
}

// PayoutCalculateParams is the request body of POST /v1/payout/calculate.
type PayoutCalculateParams struct {
	// Payout amount as a decimal string. Required. Example: "10".
	Amount Money `json:"amount"`

	// Payout asset (USDT, BTC, …). Required. Example: "USDT".
	Currency string `json:"currency"`

	// true — the fee is debited from the balance on top of the amount (the recipient gets exactly
	// amount); false — the fee is taken out of the payout.
	IsSubtract *bool `json:"is_subtract,omitempty"`

	// Payout network; required when the asset lives on several networks. Example: "tron".
	Network Network `json:"network,omitempty"`
}

// PayoutCancelParams is the request body of POST /v1/payout/cancel.
type PayoutCancelParams struct {
	// Id of the payout (or refund) to cancel. Required.
	UUID string `json:"uuid"`
}

// PayoutFeeConfigSetParams is the request body of POST /v1/payout/fee-config/set.
type PayoutFeeConfigSetParams struct {
	// true — the recipient pays the network fee (receives less); false — the merchant bears the
	// fee. Required. Example: true.
	FeeOnRecipient bool `json:"fee_on_recipient"`
}

// PayoutHistoryParams is the request body of POST /v1/payout/history.
type PayoutHistoryParams struct {
	// payout — ordinary payouts, refund — refunds; empty returns both. Example: "payout".
	Kind string `json:"kind,omitempty"`

	// Page size, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (newest first). Example: 0.
	Offset *int `json:"offset,omitempty"`

	// Filter by status (an exact value from the status vocabulary); empty returns all. Example:
	// "paid".
	Status PayoutStatus `json:"status,omitempty"`
}

// PayoutInfoParams is the request body of POST /v1/payout/info.
type PayoutInfoParams struct {
	// Your order reference. Example: "order-1".
	OrderID string `json:"order_id,omitempty"`

	// Invoice id in Oblodai. Either uuid or order_id is required; uuid takes priority.
	UUID string `json:"uuid,omitempty"`
}

// PayoutLinkParams is the request body of POST /v1/payout/link.
type PayoutLinkParams struct {
	// Amount in currency, as a string; greater than zero. Required. Example: "25".
	Amount Money `json:"amount"`

	// Payout crypto asset (USDT, BTC, …); fiat is not possible. Required. Example: "USDT".
	Currency string `json:"currency"`

	// If set, the recipient receives an email with a "Claim funds" button; a delivery failure does not
	// cancel link creation. Example: "user@example.com".
	Email string `json:"email,omitempty"`

	// Link lifetime in seconds, clamped to 3600–2592000 (one hour to 30 days); without the field or
	// with 0 the link lives 1 hour, not the maximum — set it explicitly. Example: 604800.
	ExpiresInSeconds *int `json:"expires_in_seconds,omitempty"`

	// Who pays the network fee: "recipient" (default — deducted from the amount, the recipient
	// receives less) or "merchant" (the amount plus the fee is reserved, the recipient receives
	// exactly amount). Example: "merchant".
	FeeBearer FeeBearer `json:"fee_bearer,omitempty"`

	// Payout network for the recipient (tron, bitcoin, …). Required. Example: "tron".
	Network Network `json:"network"`

	// Message to the recipient (shown on the claim page and in the email). Example: "Спасибо
	// за участие".
	Note string `json:"note,omitempty"`

	// Claim code — a second factor for the link: "auto" — we generate it and return it ONCE in the
	// response, or your own (6–64 visible characters), empty — no code. Pass the code to the
	// recipient over a channel SEPARATE from the link (it is not put into the email); after 10
	// incorrect attempts the link is locked. Example: "auto".
	Passcode string `json:"passcode,omitempty"`

	// Your deduplication key, unique per merchant; the Idempotency-Key header has no effect on this
	// endpoint. Example: "bonus-42".
	Reference string `json:"reference,omitempty"`

	// Title — shown to the recipient on the claim page. Example: "Бонус".
	Title string `json:"title,omitempty"`
}

// PayoutLinkBatchParams is the request body of POST /v1/payout/link/batch.
type PayoutLinkBatchParams struct {
	// Up to 500 links per call; each one succeeds or fails independently, the response is aligned with
	// the request indexes. Required.
	Items []PayoutLinkBatchParamsItemItem `json:"items"`
}

// PayoutLinkBatchParamsItemItem is an element of items in POST /v1/payout/link/batch.
type PayoutLinkBatchParamsItemItem struct {
	// Amount in currency, as a string; greater than zero. Required. Example: "25".
	Amount Money `json:"amount"`

	// Payout crypto asset (USDT, BTC, …); fiat is not possible. Required. Example: "USDT".
	Currency string `json:"currency"`

	// If set, the recipient receives an email with a "Claim funds" button; a delivery failure does not
	// cancel link creation. Example: "user@example.com".
	Email string `json:"email,omitempty"`

	// Link lifetime in seconds, clamped to 3600–2592000 (one hour to 30 days); without the field or
	// with 0 the link lives 1 hour, not the maximum — set it explicitly. Example: 604800.
	ExpiresInSeconds *int `json:"expires_in_seconds,omitempty"`

	// Who pays the network fee: "recipient" (default — deducted from the amount, the recipient
	// receives less) or "merchant" (the amount plus the fee is reserved, the recipient receives
	// exactly amount). Example: "merchant".
	FeeBearer FeeBearer `json:"fee_bearer,omitempty"`

	// Payout network for the recipient (tron, bitcoin, …). Required. Example: "tron".
	Network Network `json:"network"`

	// Message to the recipient (shown on the claim page and in the email). Example: "Спасибо
	// за участие".
	Note string `json:"note,omitempty"`

	// Claim code — a second factor for the link: "auto" — we generate it and return it ONCE in the
	// response, or your own (6–64 visible characters), empty — no code. Pass the code to the
	// recipient over a channel SEPARATE from the link (it is not put into the email); after 10
	// incorrect attempts the link is locked. Example: "auto".
	Passcode string `json:"passcode,omitempty"`

	// Your deduplication key, unique per merchant; the Idempotency-Key header has no effect on this
	// endpoint. Required. Example: "bonus-42".
	Reference string `json:"reference"`

	// Title — shown to the recipient on the claim page. Example: "Бонус".
	Title string `json:"title,omitempty"`
}

// PayoutLinkCancelParams is the request body of POST /v1/payout/link/cancel.
type PayoutLinkCancelParams struct {
	// Payout link id (link_id from the creation response). Required.
	LinkID string `json:"link_id"`
}

// PayoutLinkChequeParams is the request body of POST /v1/payout/link/cheque.
type PayoutLinkChequeParams struct {
	// Claim secret from the payout link creation response. Stored only as a hash and never reissued
	// — the cheque can be printed only while you still hold the token. Required. Example:
	// "nUqx1yG3…".
	ClaimToken string `json:"claim_token"`

	// Document language — one of the 41 supported codes (en by default); the full list is in the
	// document.unknown_lang error. Example: "ru".
	Lang string `json:"lang,omitempty"`
}

// PayoutLinkInfoParams is the request body of POST /v1/payout/link/info.
type PayoutLinkInfoParams struct {
	// Payout link id (link_id from the creation response). Required.
	LinkID string `json:"link_id"`
}

// PayoutLinkListParams is the request body of POST /v1/payout/link/list.
type PayoutLinkListParams struct {
	// How many links to return per page. Example: 50.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (paging). Example: 0.
	Offset *int `json:"offset,omitempty"`
}

// PayoutMassParams is the request body of POST /v1/payout/mass.
type PayoutMassParams struct {
	// Array of up to 100 items; the fields of each are as in POST /v1/payout. Required.
	Payouts []PayoutMassParamsPayoutItem `json:"payouts"`

	// Origin label, applied to every item without its own source.
	Source string `json:"source,omitempty"`
}

// PayoutMassParamsPayoutItem is an element of payouts in POST /v1/payout/mass.
type PayoutMassParamsPayoutItem struct {
	// Recipient address. Required.
	Address string `json:"address"`

	// Payout amount, in currency. Required. Example: "25".
	Amount Money `json:"amount"`

	// Currency code (for example USDT). Required. Example: "USDT".
	Currency string `json:"currency"`

	// Fund the payout by converting the balance. USDT → currency only. Example: "USDT".
	FromCurrency string `json:"from_currency,omitempty"`

	// Who pays the network fee: true — amount+fee is debited from the balance and the recipient
	// receives amount; false — the recipient receives amount-fee; not provided — the project
	// fee-config.
	IsSubtract *bool `json:"is_subtract,omitempty"`

	// Destination tag/memo (TON Jetton). Maximum 120 characters.
	Memo string `json:"memo,omitempty"`

	// Network (tron, ethereum, …). Required for coins with several networks. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Your payout number; idempotency key. Required. Example: "payout-1".
	OrderID string `json:"order_id"`

	// Origin label: api (default) or manual.
	Source string `json:"source,omitempty"`

	// Custom webhook URL for this payout (passes the SSRF check). Requires a registered endpoint (POST
	// /v1/webhooks): delivery is signed with its secret.
	URLCallback string `json:"url_callback,omitempty"`
}

// PayoutRefundFeeConfigSetParams is the request body of POST /v1/payout/refund-fee-config/set.
type PayoutRefundFeeConfigSetParams struct {
	// true — the customer receives net (the customer pays the fee); false — the merchant pays the
	// fee and the customer receives gross. Required. Example: true.
	FeeOnCustomer bool `json:"fee_on_customer"`
}

// PayoutServicesParams is the request body of POST /v1/payout/services.
type PayoutServicesParams struct {
	// Page size, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (newest first). Example: 0.
	Offset *int `json:"offset,omitempty"`
}

// PayoutValidateParams is the request body of POST /v1/payout/validate.
type PayoutValidateParams struct {
	// Recipient address. Required.
	Address string `json:"address"`

	// Payout amount, in currency. Required. Example: "25".
	Amount Money `json:"amount"`

	// Currency code (for example USDT). Required. Example: "USDT".
	Currency string `json:"currency"`

	// Fund the payout by converting the balance. USDT → currency only. Example: "USDT".
	FromCurrency string `json:"from_currency,omitempty"`

	// Who pays the network fee: true — amount+fee is debited from the balance and the recipient
	// receives amount; false — the recipient receives amount-fee; not provided — the project
	// fee-config.
	IsSubtract *bool `json:"is_subtract,omitempty"`

	// Destination tag/memo (TON Jetton). Maximum 120 characters.
	Memo string `json:"memo,omitempty"`

	// Network (tron, ethereum, …). Required for coins with several networks. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Your payout number; idempotency key. Required. Example: "payout-1".
	OrderID string `json:"order_id"`

	// Origin label: api (default) or manual.
	Source string `json:"source,omitempty"`

	// Custom webhook URL for this payout (passes the SSRF check). Requires a registered endpoint (POST
	// /v1/webhooks): delivery is signed with its secret.
	URLCallback string `json:"url_callback,omitempty"`
}

// RefundBatchParams is the request body of POST /v1/refund/batch.
type RefundBatchParams struct {
	// What to do when an item fails: continue (default) — process the rest; stop — halt processing
	// after the first error. Example: "continue".
	OnError BatchOnError `json:"on_error,omitempty"`

	// Array of 1 to 5000 items — the same fields as POST /v1/payment/refund; every item requires
	// reference (idempotency key) and either uuid or order_id of the payment. Required.
	Refunds []RefundBatchParamsRefundItem `json:"refunds"`
}

// RefundBatchParamsRefundItem is an element of refunds in POST /v1/refund/batch.
type RefundBatchParamsRefundItem struct {
	// Refund destination address. Defaults to the payment's payer_address; required only for
	// Bitcoin/UTXO.
	Address string `json:"address,omitempty"`

	// Partial amount. Defaults to the full amount received. Example: "10".
	Amount Money `json:"amount,omitempty"`

	// Network. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Your order reference for the payment. Either uuid or order_id is required. Example: "order-1".
	OrderID string `json:"order_id,omitempty"`

	// Optional refund idempotency key: distinguishes two different refunds with the same (payment,
	// address, amount); a repeat with the same value is deduplicated. This is not order_id. Required.
	Reference string `json:"reference"`

	// Payment id. Either uuid or order_id is required.
	UUID string `json:"uuid,omitempty"`
}

// SandboxDepositParams is the request body of POST /v1/sandbox/deposit.
type SandboxDepositParams struct {
	// Amount in the invoice currency; empty — pay exactly what is due, anything else is a way to
	// produce an under/overpayment. Example: "10".
	Amount Money `json:"amount,omitempty"`

	// How many confirmations the deposit arrived with; 0 — fully confirmed; fewer than required —
	// a way to test the pending→confirmed transition (repeat the same txid with a higher number).
	// Example: 0.
	Confirmations *int `json:"confirmations,omitempty"`

	// UUID of the test invoice being "paid". Required.
	InvoiceID string `json:"invoice_id"`

	// Repeating the same txid tests your idempotency; empty — a new txid.
	TxID string `json:"txid,omitempty"`
}

// SandboxFaucetParams is the request body of POST /v1/sandbox/faucet.
type SandboxFaucetParams struct {
	// Amount of test money, as a string; capped at 1000000 per call. Required. Example: "1000".
	Amount Money `json:"amount"`

	// Top-up asset (USDT, BTC, …). Required. Example: "USDT".
	Asset string `json:"asset"`

	// Safe-retry key; empty — every call creates a new top-up.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
}

// SandboxWebhooksReplayParams is the request body of POST /v1/sandbox/webhooks/replay.
type SandboxWebhooksReplayParams struct {
	// Delivery id from GET /v1/sandbox/webhooks. Required.
	DeliveryID string `json:"delivery_id"`
}

// SplitConfigSetParams is the request body of POST /v1/split/config/set.
type SplitConfigSetParams struct {
	// How many seconds to defer split settlement; range 0–7776000 (up to 90 days). 0 — send the
	// shares immediately: you take on the risk that a refund becomes impossible. Required. Example:
	// 172800.
	RefundHoldSeconds int `json:"refund_hold_seconds"`
}

// SplitRecipientOptinParams is the request body of POST /v1/split/recipient/optin.
type SplitRecipientOptinParams struct {
	// Allow other merchants to route split shares to your balance. true — enable receiving, false
	// — disable (new rules targeting you stop being created; existing ones keep executing).
	// Required. Example: true.
	Enabled bool `json:"enabled"`
}

// SplitRuleParams is the request body of POST /v1/split/rule.
type SplitRuleParams struct {
	// External crypto address of the partner; the share leaves as a real on-chain transaction —
	// irreversible. Exactly one recipient option: either address+network or merchant_id.
	Address string `json:"address,omitempty"`

	// Id of the partner merchant inside Oblodai; the share moves through internal accounting and is
	// clawed back on a refund. Example: "b4c1f0e2-5a77-4d31-9f08-2c6e7a1b3d94".
	MerchantID string `json:"merchant_id,omitempty"`

	// Address network. Required together with address. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Comment for yourself (shown in the rule list).
	Note string `json:"note,omitempty"`

	// Share of every payment, as a string: "10" = 10 %, "2.5" = 2.5 %. Greater than 0 and at most 100,
	// step 0.01 %; the sum of all rules cannot exceed 100 %. Required. Example: "10".
	Percent string `json:"percent"`
}

// SplitRuleDeleteParams is the request body of POST /v1/split/rule/delete.
type SplitRuleDeleteParams struct {
	// Rule identifier from POST /v1/split/rule or the list. Required. Example:
	// "9f4c1a2b-77de-4a55-9c1f-0e2b3d4a5f60".
	RuleID string `json:"rule_id"`
}

// SplitRuleListParams is the request body of POST /v1/split/rule/list.
type SplitRuleListParams struct {
	// Page size, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (newest first). Example: 0.
	Offset *int `json:"offset,omitempty"`
}

// TestWebhookPaymentParams is the request body of POST /v1/test-webhook/payment.
type TestWebhookPaymentParams struct {
	// Currency in the body. Example: "USDT".
	Currency string `json:"currency,omitempty"`

	// Network in the body. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Your order_id, which is put into the test event body.
	OrderID string `json:"order_id,omitempty"`

	// Status in the body — from the status dictionary of this event type. Default paid (confirmed
	// for a payout). Example: "paid".
	Status PaymentStatus `json:"status,omitempty"`

	// Where to send the test body. Required. Example: "https://shop.example/oblodai/callback".
	URLCallback string `json:"url_callback"`

	// UUID of the object (payment, wallet or payout) put into the test event body.
	UUID string `json:"uuid,omitempty"`
}

// TestWebhookPayoutParams is the request body of POST /v1/test-webhook/payout.
type TestWebhookPayoutParams struct {
	// Currency in the body. Example: "USDT".
	Currency string `json:"currency,omitempty"`

	// Network in the body. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Your order_id, which is put into the test event body.
	OrderID string `json:"order_id,omitempty"`

	// Status in the body — from the status dictionary of this event type. Default paid (confirmed
	// for a payout). Example: "paid".
	Status PayoutStatus `json:"status,omitempty"`

	// Where to send the test body. Required. Example: "https://shop.example/oblodai/callback".
	URLCallback string `json:"url_callback"`

	// UUID of the object (payment, wallet or payout) put into the test event body.
	UUID string `json:"uuid,omitempty"`
}

// TestWebhookWalletParams is the request body of POST /v1/test-webhook/wallet.
type TestWebhookWalletParams struct {
	// Currency in the body. Example: "USDT".
	Currency string `json:"currency,omitempty"`

	// Network in the body. Example: "tron".
	Network Network `json:"network,omitempty"`

	// Your order_id, which is put into the test event body.
	OrderID string `json:"order_id,omitempty"`

	// Status in the body — from the status dictionary of this event type. Default paid (confirmed
	// for a payout). Example: "paid".
	Status string `json:"status,omitempty"`

	// Where to send the test body. Required. Example: "https://shop.example/oblodai/callback".
	URLCallback string `json:"url_callback"`

	// UUID of the object (payment, wallet or payout) put into the test event body.
	UUID string `json:"uuid,omitempty"`
}

// TransferBatchParams is the request body of POST /v1/transfer/batch.
type TransferBatchParams struct {
	// What to do when an item fails: continue (default) — process the rest; stop — halt processing
	// after the first error. Example: "continue".
	OnError BatchOnError `json:"on_error,omitempty"`

	// Array of 1 to 5000 items — the same fields as POST /v1/transfer/to-user; every item requires
	// order_id (idempotency key) and to_user_id (user UUID).
	Transfers []TransferBatchParamsTransferItem `json:"transfers,omitempty"`
}

// TransferBatchParamsTransferItem is an element of transfers in POST /v1/transfer/batch.
type TransferBatchParamsTransferItem struct {
	// Transfer amount in currency. Required. Example: "50".
	Amount Money `json:"amount"`

	// Currency code (cryptocurrency). Required. Example: "USDT".
	Currency string `json:"currency"`

	// Idempotency key: a repeat with the same order_id is a no-op; required in a transfer batch.
	// Required.
	OrderID string `json:"order_id"`

	// Platform user id of the recipient (UUID, not username); a username is resolved to an id via the
	// cabinet public profile /public/users/{username}. Required.
	ToUserID string `json:"to_user_id"`
}

// TransferToPersonalParams is the request body of POST /v1/transfer/to-personal.
type TransferToPersonalParams struct {
	// Transfer amount in currency. Required. Example: "50".
	Amount Money `json:"amount"`

	// Currency code (cryptocurrency). Required. Example: "USDT".
	Currency string `json:"currency"`

	// Idempotency key: a repeat with the same order_id is a no-op. Always send it, otherwise retrying
	// the request after a network timeout creates a second transfer. Example: "transfer-1".
	OrderID string `json:"order_id,omitempty"`
}

// TransferToUserParams is the request body of POST /v1/transfer/to-user.
type TransferToUserParams struct {
	// Transfer amount in currency. Required. Example: "50".
	Amount Money `json:"amount"`

	// Currency code (cryptocurrency). Required. Example: "USDT".
	Currency string `json:"currency"`

	// Idempotency key: a repeat with the same order_id is a no-op; required in a transfer batch.
	OrderID string `json:"order_id,omitempty"`

	// Platform user id of the recipient (UUID, not username); a username is resolved to an id via the
	// cabinet public profile /public/users/{username}. Required.
	ToUserID string `json:"to_user_id"`
}

// VRCSParams is the request body of POST /v1/vrcs.
type VRCSParams struct {
	// true — enable auto-conversion of volatile deposits to USDT, false — disable; omit to read
	// the current state. Example: true.
	Enabled *bool `json:"enabled,omitempty"`
}

// WalletParams is the request body of POST /v1/wallet.
type WalletParams struct {
	// Symbol of the receiving currency (USDT, BTC, ETH, …). Required. Example: "USDT".
	Currency string `json:"currency"`

	// Receiving network (tron, ethereum, bitcoin, …). Required. Example: "tron".
	Network Network `json:"network"`

	// Your customer/order identifier. Pins a dedicated permanent address to the customer. Example:
	// "client-42".
	OrderID string `json:"order_id,omitempty"`
}

// WalletBlockParams is the request body of POST /v1/wallet/block.
type WalletBlockParams struct {
	// Static wallet address. Required. Example: "TXk9...c3Fd".
	Address string `json:"address"`

	// true — block (the default when the field is omitted); false — unblock.
	IsForceBlock *bool `json:"is_force_block,omitempty"`
}

// WalletBlockedAddressRefundParams is the request body of POST /v1/wallet/blocked-address-refund.
type WalletBlockedAddressRefundParams struct {
	// Refund destination address. Required.
	Address string `json:"address"`

	// Destination tag/memo (XRP destination tag, XLM memo id, TON comment). Required for a classic
	// address on a tag/memo network if the tag is not embedded in the X-/M-address.
	Memo string `json:"memo,omitempty"`

	// Static wallet id (from the /v1/wallet response). Required.
	UUID string `json:"uuid"`
}

// WalletQRParams is the request body of POST /v1/wallet/qr.
type WalletQRParams struct {
	// Arbitrary address to render into a QR code (PNG as a data: URI). Required.
	Address string `json:"address"`
}

// WebhooksParams is the request body of POST /v1/webhooks.
type WebhooksParams struct {
	// HTTPS callback URL. SSRF check: private and local addresses are rejected. Required. Example:
	// "https://shop.example/oblodai/callback".
	URL string `json:"url"`
}

// WebhooksDeliveriesParams is the request body of POST /v1/webhooks/deliveries.
type WebhooksDeliveriesParams struct {
	// Page size, 1–100; out of range falls back to 25. Example: 25.
	Limit *int `json:"limit,omitempty"`

	// Offset from the start of the list (newest first). Example: 0.
	Offset *int `json:"offset,omitempty"`
}
