// Code generated by internal/codegen from contract/contract.json (core 7b8eb828b9ec). DO NOT EDIT.

package oblodai

const (
	// ContractCoreCommit is the core revision the contract snapshot was exported from.
	ContractCoreCommit = "7b8eb828b9ec3bbaff44755ad784881e533ec4fb"
	// ContractExportedAt is when that snapshot was taken.
	ContractExportedAt = "2026-08-25T22:08:54Z"
	// ContractHash is the SHA-256 of contract/contract.json; it identifies the wire contract.
	ContractHash = "e09b495accaeacda1aa889a8c56b0e9ee18b5236dc3c2c29222e7ee849e7c5ee"
)
