// Code generated by internal/codegen from contract/contract.json (core 7ec04293c426). DO NOT EDIT.

package oblodai

const (
	// ContractCoreCommit is the core revision the contract snapshot was exported from.
	ContractCoreCommit = "7ec04293c4264faa121409b1715c2e8fcd349f32"
	// ContractExportedAt is when that snapshot was taken.
	ContractExportedAt = "2026-08-26T10:50:02Z"
	// ContractHash is the SHA-256 of contract/contract.json; it identifies the wire contract.
	ContractHash = "c2d8d4b733eaa4a876a1f8d0525cb838df380ee37fc0d03a711dab77e80b2829"
)
