// Code generated by oblodai-backend tools/sdkgen from openapi.json. DO NOT EDIT.

// The request-signing protocol of the core (x-oblodai-signing): the headers a signed request
// carries, the canonical string the signature covers and the limits the core enforces. The
// hand-written runtime signs with these and nothing else, so a change in the contract reaches
// every request through generation alone. Webhook delivery headers are in package webhooks.

package oblodai

// Headers the core reads on a signed request.
const (
	// HeaderPublicID carries the merchant's public key id.
	HeaderPublicID = "X-Public-Id"
	// HeaderSignature carries the hex HMAC-SHA256 of the canonical request string.
	HeaderSignature = "X-Signature"
	// HeaderTimestamp carries the unix time in seconds the request was signed at.
	HeaderTimestamp = "X-Timestamp"
	// HeaderIdempotencyKey carries the key the core deduplicates a write by; it is signed.
	HeaderIdempotencyKey = "Idempotency-Key"
)

// SignatureSkewSeconds is how far the core lets a request timestamp drift from its own clock, and
// how far a webhook delivery's timestamp may be from the receiver's.
const SignatureSkewSeconds = 300

// MaxRequestBodyBytes is the largest request body the core reads, in bytes.
const MaxRequestBodyBytes = 1048576

// MaxIdempotencyKeyLength is the longest idempotency key the core accepts.
const MaxIdempotencyKeyLength = 255

// canonicalRequest is the string a request signature covers:
// ts + sep + METHOD + sep + request_uri + sep + idempotency_key + sep + body, sep = "\n".
// ts is unix seconds in decimal, method upper case, requestURI the path plus raw query, the
// idempotency key empty when none is sent (the separator stays), body the exact bytes sent.
func canonicalRequest(ts, method, requestURI, idempotencyKey string, body []byte) []byte {
	var out []byte
	out = append(out, ts...)
	out = append(out, "\n"...)
	out = append(out, method...)
	out = append(out, "\n"...)
	out = append(out, requestURI...)
	out = append(out, "\n"...)
	out = append(out, idempotencyKey...)
	out = append(out, "\n"...)
	out = append(out, body...)
	return out
}

// canonicalWebhook is the string a webhook delivery signature covers:
// ts + sep + payload, sep = ".".
// ts is unix seconds in decimal, payload the raw delivery body.
func canonicalWebhook(ts string, payload []byte) []byte {
	var out []byte
	out = append(out, ts...)
	out = append(out, "."...)
	out = append(out, payload...)
	return out
}
