// Code generated by oblodai-backend tools/sdkgen from openapi.json. DO NOT EDIT.

// Facts of the API the hand-written runtime works from: which operations are long-running and how
// their jobs are followed (x-sdk-poll), and which numeric request fields are not money.

package oblodai

// LRO maps each long-running create operation (operationId) to the operation that polls its job.
var LRO = map[string]string{
	"createDocumentJob":   "getDocumentJob",
	"createPaymentBatch":  "getBatchInfo",
	"createPayoutBatch":   "getBatchInfo",
	"createRefundBatch":   "getBatchInfo",
	"createTransferBatch": "getBatchInfo",
}

// Polls maps each poll operation (operationId) to how its jobs are followed.
var Polls = map[string]Poll{
	"getBatchInfo": {
		IDField:     "batch_id",
		StatusField: "status",
		Terminal:    []string{"completed", "stopped"},
	},
	"getDocumentJob": {
		IDField:     "job_id",
		StatusField: "status",
		Terminal:    []string{"done", "failed", "expired"},
		Download:    "downloadDocumentJobFile",
	},
}

// TerminalStatuses are the terminal statuses of every poll, without repeats: after one of them a
// job no longer changes.
var TerminalStatuses = []string{"completed", "stopped", "done", "failed", "expired"}

// pollModels makes an empty answer of each poll operation: the model a Job of it decodes into.
var pollModels = map[string]func() any{
	"getBatchInfo":   func() any { return new(BatchInfoResponse) },
	"getDocumentJob": func() any { return new(DocumentJobView) },
}

// nonMoneyNumbers are the JSON names of the numeric request fields that are not money: a JSON
// number with a fraction under any other name in a request body is refused before it is sent.
var nonMoneyNumbers = map[string]bool{
	"accuracy_payment_percent": true,
}
