// Code generated by oblodai-backend tools/sdkgen from openapi.json. DO NOT EDIT.

// Kinds of webhook event and their typed bodies, from the contract's webhooks: the kind is the
// const of the type field of each event's body schema.

package webhooks

import "github.com/oblodai/oblodai-go/v2"

// Kinds of event (Event.Type) this release models.
const (
	KindConversion = "conversion"
	KindPayment    = "payment"
	KindPayout     = "payout"
	KindWallet     = "wallet"
)

// KnownKinds are the kinds this release models with a typed body, sorted.
var KnownKinds = []string{KindConversion, KindPayment, KindPayout, KindWallet}

// EventKinds maps each event name (X-Webhook-Event) to its kind.
var EventKinds = map[string]string{
	"conversion.completed":   KindConversion,
	"conversion.refunded":    KindConversion,
	"invoice.cancelled":      KindPayment,
	"invoice.confirm_check":  KindPayment,
	"invoice.created":        KindPayment,
	"invoice.expired":        KindPayment,
	"invoice.paid":           KindPayment,
	"invoice.paid_over":      KindPayment,
	"invoice.select":         KindPayment,
	"invoice.under_review":   KindPayment,
	"invoice.wrong_amount":   KindPayment,
	"payout.approved":        KindPayout,
	"payout.awaiting_cosign": KindPayout,
	"payout.broadcasting":    KindPayout,
	"payout.cancelled":       KindPayout,
	"payout.confirmed":       KindPayout,
	"payout.failed":          KindPayout,
	"payout.pending":         KindPayout,
	"payout.sent":            KindPayout,
	"wallet.paid":            KindWallet,
}

// IDFields maps each kind to the body field holding the id of the object the event is about, as
// the contract declares it; a kind whose body has no such field is not listed.
var IDFields = map[string]string{
	KindConversion: "id",
	KindPayment:    "uuid",
	KindPayout:     "uuid",
	KindWallet:     "uuid",
}

// Bodies holds the typed body of an event: for a kind this release models exactly one is set, for
// any other none is.
type Bodies struct {
	// Conversion is the body of a "conversion" event (conversion.completed, conversion.refunded).
	Conversion *oblodai.ConversionWebhook
	// Payment is the body of a "payment" event (invoice.cancelled, invoice.confirm_check, invoice.created, invoice.expired, invoice.paid, invoice.paid_over, invoice.select, invoice.under_review, invoice.wrong_amount).
	Payment *oblodai.PaymentWebhook
	// Payout is the body of a "payout" event (payout.approved, payout.awaiting_cosign, payout.broadcasting, payout.cancelled, payout.confirmed, payout.failed, payout.pending, payout.sent).
	Payout *oblodai.PayoutWebhook
	// Wallet is the body of a "wallet" event (wallet.paid).
	Wallet *oblodai.WalletWebhook
}

// target sets the empty body of kind and returns it to decode into; nil for a kind this release
// does not model.
func (b *Bodies) target(kind string) any {
	switch kind {
	case KindConversion:
		b.Conversion = new(oblodai.ConversionWebhook)
		return b.Conversion
	case KindPayment:
		b.Payment = new(oblodai.PaymentWebhook)
		return b.Payment
	case KindPayout:
		b.Payout = new(oblodai.PayoutWebhook)
		return b.Payout
	case KindWallet:
		b.Wallet = new(oblodai.WalletWebhook)
		return b.Wallet
	}
	return nil
}

// known reports whether a typed body is set.
func (b *Bodies) known() bool {
	return b.Conversion != nil || b.Payment != nil || b.Payout != nil || b.Wallet != nil
}
