// Code generated by oblodai-backend tools/sdkgen from openapi.json. DO NOT EDIT.

// The headers the core sets on a webhook delivery (x-oblodai-signing.webhook.headers and
// webhook.test_header).

package webhooks

// Delivery headers.
const (
	// HeaderTimestamp is the unix time in seconds this attempt was signed and sent at.
	HeaderTimestamp = "X-Webhook-Timestamp"
	// HeaderSignature is the hex HMAC-SHA256 of the delivery with the current secret.
	HeaderSignature = "X-Webhook-Signature"
	// HeaderSignaturePrev is the same with the previous secret, during a rotation overlap only.
	HeaderSignaturePrev = "X-Webhook-Signature-Prev"
	// HeaderEvent is the event name, a key of EventKinds.
	HeaderEvent = "X-Webhook-Event"
	// HeaderID is stable per delivery: identical across the retries of that delivery.
	HeaderID = "X-Webhook-Id"
	// HeaderEventID is stable per state: the same for a resend of a state already delivered.
	HeaderEventID = "X-Webhook-Event-Id"
	// HeaderEventTime is the unix time in seconds the state change committed.
	HeaderEventTime = "X-Webhook-Event-Time"
	// HeaderTest is "true" on a rehearsal (test) delivery and absent from a live one
	// (x-oblodai-signing.webhook.test_header).
	HeaderTest = "X-Webhook-Test"
)

// EventIDField is the signed body field carrying the id of the object state
// (x-oblodai-signing.webhook.event_id_field): deduplicate on it. Headers are not signed. A delivery
// from an older core may lack the field; then deduplicate on type:id:sequence from the body.
const EventIDField = "event_id"
